"""Add processed fields to PostReport and admin reports

Revision ID: bbc69313308d
Revises: 
Create Date: 2025-11-21 00:44:13.947662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc69313308d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('last_post_time', sa.DateTime(), nullable=True),
    sa.Column('captcha_fail_count', sa.Integer(), nullable=False),
    sa.Column('last_captcha_fail_time', sa.DateTime(), nullable=True),
    sa.Column('post_cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('cooldown_reason', sa.String(length=255), nullable=True),
    sa.Column('post_comment_counts', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('ücretsiz', 'premium', 'dev', 'caylak_admin', 'usta_admin', 'kurucu', name='userrole'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('browser_fingerprint', sa.String(length=256), nullable=True),
    sa.Column('backup_code', sa.String(length=10), nullable=True),
    sa.Column('session_token', sa.String(length=36), nullable=True),
    sa.Column('role_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('action_count', sa.Integer(), nullable=True),
    sa.Column('last_action_time', sa.DateTime(), nullable=True),
    sa.Column('limit_hit_count', sa.Integer(), nullable=True),
    sa.Column('profile_pic_url', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('selected_language', sa.String(length=5), nullable=True),
    sa.Column('device_1_fingerprint', sa.String(length=256), nullable=True),
    sa.Column('device_1_name', sa.String(length=100), nullable=True),
    sa.Column('device_1_last_login', sa.DateTime(), nullable=True),
    sa.Column('device_2_fingerprint', sa.String(length=256), nullable=True),
    sa.Column('device_2_name', sa.String(length=100), nullable=True),
    sa.Column('device_2_last_login', sa.DateTime(), nullable=True),
    sa.Column('receipt_fail_count', sa.Integer(), nullable=False),
    sa.Column('last_receipt_fail_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('session_token'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_browser_fingerprint'), ['browser_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_device_1_fingerprint'), ['device_1_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_device_2_fingerprint'), ['device_2_fingerprint'], unique=False)

    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('original_file_name', sa.String(length=255), nullable=True),
    sa.Column('original_file_size_mb', sa.Float(), nullable=True),
    sa.Column('modified_files_count', sa.Integer(), nullable=True),
    sa.Column('modified_files_names', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('feature_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_usage_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_usage_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('mute_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('mute_end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mute_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mute_log_mute_end_time'), ['mute_end_time'], unique=False)

    op.create_table('page_visit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=50), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)

    op.create_table('purchase_intent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=20), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('customer_name', sa.String(length=50), nullable=True),
    sa.Column('customer_phone', sa.String(length=25), nullable=True),
    sa.Column('customer_email', sa.String(length=50), nullable=True),
    sa.Column('receipt_image_path', sa.String(length=255), nullable=True),
    sa.Column('payment_notified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intent_id')
    )
    op.create_table('temporary_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    with op.batch_alter_table('temporary_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temporary_file_request_id'), ['request_id'], unique=False)

    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by_admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('video_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_key', sa.String(length=50), nullable=False),
    sa.Column('watch_time_seconds', sa.Integer(), nullable=True),
    sa.Column('last_watched_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_admin_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('MESSAGE_SENT', 'TICKET_CLAIMED', 'TICKET_RELEASED', 'TICKET_CLOSED', name='chatadminlogaction'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.Column('attachment_name', sa.String(length=255), nullable=True),
    sa.Column('is_admin_message', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_timestamp'), ['timestamp'], unique=False)

    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='_user_post_like_uc')
    )
    op.create_table('post_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('processed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['processed_by_admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_report')
    op.drop_table('post_media')
    op.drop_table('like')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_timestamp'))

    op.drop_table('comment')
    op.drop_table('chat_message')
    op.drop_table('chat_admin_log')
    op.drop_table('video_log')
    op.drop_table('user_permissions')
    op.drop_table('ticket')
    with op.batch_alter_table('temporary_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temporary_file_request_id'))

    op.drop_table('temporary_file')
    op.drop_table('purchase_intent')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))

    op.drop_table('post')
    op.drop_table('page_visit_log')
    with op.batch_alter_table('mute_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mute_log_mute_end_time'))

    op.drop_table('mute_log')
    with op.batch_alter_table('feature_usage_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_usage_log_timestamp'))

    op.drop_table('feature_usage_log')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_timestamp'))

    op.drop_table('activity_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_device_2_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_user_device_1_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_user_browser_fingerprint'))

    op.drop_table('user')
    op.drop_table('permission')
    # ### end Alembic commands ###
